name: GitHub Actions Demo
on: [push]
jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      - uses: actions/checkout@v3 #permet de récupérer les fichiers dans git
      - run: ls -la
      - run: pip3 install pytest
      - run: pytest test_lib.py
      
      - name: Upload logs.txt file
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-logs
          path: logs.txt #je veux pouvoir accéder à logs.txt