name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      - uses: actions/checkout@v3 #permet de récupérer les fichiers dans git
      - run: ls -la
      - run: python3 test_lib.py
      