name: GitHub Actions Demo
on: [push]
jobs:
  Unit tests:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      - uses: actions/checkout@v3 #permet de récupérer les fichiers dans git
      - run: ls -la
      - run: pip3 install pytest
      - run: pytest test_lib.py
      
  End to end tests:
    runs-on: ubuntu-latest
    steps:
        - run: cypress run
    
  Deploy:
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v3 #permet de récupérer les fichiers du dépot git
        - run: deployment/deploy.sh